# 5 demo patients with varied risk profiles, drawn from new dataset schema.
# Mock names added; weather data is representative of dataset values.

PATIENTS = [
    {
        "id": "1",
        "name": "Maria Santos",
        "dob": "1962-04-15",
        "gender": "F",
        "mrn": "00482910",
        "age": 62.0,
        "specialty": "physiotherapy",
        "appointment_time": "14:30",
        "appointment_date": "2021-09-09",
        "appointment_shift": "afternoon",
        "city": "ITAJAÍ",
        "under_12_years_old": 0,
        "over_60_years_old": 1,
        "patient_needs_companion": 1,
        "disability": "",
        "rainy_day_before": 1,
        "storm_day_before": 0,
        "rain_intensity": "weak",
        "heat_intensity": "mild",
        "average_temp_day": 20.75,
        "average_rain_day": 0.01,
    },
    {
        "id": "2",
        "name": "Carlos Oliveira",
        "dob": "1985-09-22",
        "gender": "M",
        "mrn": "00391847",
        "age": 38.0,
        "specialty": "psychotherapy",
        "appointment_time": "09:00",
        "appointment_date": "2021-10-15",
        "appointment_shift": "morning",
        "city": "NAVEGANTES",
        "under_12_years_old": 0,
        "over_60_years_old": 0,
        "patient_needs_companion": 0,
        "disability": "",
        "rainy_day_before": 1,
        "storm_day_before": 1,
        "rain_intensity": "heavy",
        "heat_intensity": "cold",
        "average_temp_day": 15.2,
        "average_rain_day": 12.5,
    },
    {
        "id": "3",
        "name": "Ana Lima",
        "dob": "1990-01-30",
        "gender": "F",
        "mrn": "00574923",
        "age": 34.0,
        "specialty": "speech therapy",
        "appointment_time": "10:30",
        "appointment_date": "2021-11-03",
        "appointment_shift": "morning",
        "city": "B. CAMBORIU",
        "under_12_years_old": 0,
        "over_60_years_old": 0,
        "patient_needs_companion": 0,
        "disability": "",
        "rainy_day_before": 0,
        "storm_day_before": 0,
        "rain_intensity": "no_rain",
        "heat_intensity": "warm",
        "average_temp_day": 26.0,
        "average_rain_day": 0.0,
    },
    {
        "id": "4",
        "name": "José Ferreira",
        "dob": "1948-11-05",
        "gender": "M",
        "mrn": "00283746",
        "age": 75.0,
        "specialty": "occupational therapy",
        "appointment_time": "15:00",
        "appointment_date": "2021-09-20",
        "appointment_shift": "afternoon",
        "city": "CAMBORIU",
        "under_12_years_old": 0,
        "over_60_years_old": 1,
        "patient_needs_companion": 1,
        "disability": "motor",
        "rainy_day_before": 0,
        "storm_day_before": 0,
        "rain_intensity": "no_rain",
        "heat_intensity": "mild",
        "average_temp_day": 21.5,
        "average_rain_day": 0.0,
    },
    {
        "id": "5",
        "name": "Beatriz Costa",
        "dob": "2015-07-18",
        "gender": "F",
        "mrn": "00619283",
        "age": 8.0,
        "specialty": "speech therapy",
        "appointment_time": "09:30",
        "appointment_date": "2021-10-01",
        "appointment_shift": "morning",
        "city": "ITAPEMA",
        "under_12_years_old": 1,
        "over_60_years_old": 0,
        "patient_needs_companion": 1,
        "disability": "intellectual",
        "rainy_day_before": 1,
        "storm_day_before": 0,
        "rain_intensity": "moderate",
        "heat_intensity": "mild",
        "average_temp_day": 19.0,
        "average_rain_day": 3.2,
    },
]
